# Generated by Django 3.1.2 on 2020-10-31 20:24

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Deployment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service', models.CharField(choices=[('github', 'GitHub')], max_length=30, verbose_name='service')),
                ('delivery', models.CharField(blank=True, max_length=1024, verbose_name='delivery identifier')),
                ('date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date')),
            ],
            options={
                'verbose_name': 'deployment',
                'verbose_name_plural': 'deployments',
                'db_table': 'deployments',
                'ordering': ('-date',),
            },
        ),
    ]
